tasks:
  hello-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
        cd /opt/
        sonar-scanner \    
         -Dsonar.projectKey=pythonone \
         -Dsonar.sources=. \   
         -Dsonar.host.url=http://3.7.69.100:9000 \   
         -Dsonar.login=efd43a1aa1a9c374a607e08d049fe3facde71932 \
   
