tasks:
  hello-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
        sonar-scanner \
         -Dsonar.projectKey=pythontwo \
         -Dsonar.sources=. \
         -Dsonar.host.url=http://3.7.69.100:9000 \
         -Dsonar.login=7bac56fb2fdb64c5fc728dde6e1992a936751013
