tasks:
  hello-job:
    runner: razorci/python
    steps:
   
    - checkout    
    - commands:
      - |
        sonar-scanner \
         -Dsonar.projectKey=pythonone \
         -Dsonar.sources=. \
         -Dsonar.host.url=http://${SONAR_WEB_HOST} \
         -Dsonar.login=${TOKEN} \
   
